main: su.nightexpress.excellenteconomy.EconomyPlugin
version: '${version}'
name: ExcellentEconomy
author: NightExpress
desciption: A modern, lightweight economy plugin that lets you create unlimited custom currencies. 
load: STARTUP
api-version: '26.2'
folia-supported: true
depend: [ nightcore ]
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints